### ISSUE TITLE
Fixing plugin with Umbraco v7.3

### ISSUE THREAD

**Issue by Korayem** [mirabeau-nl/uTransporter#1]
As soon as I open the dashboard, I get the following JS errors:

> Request error: The URL returned a 404 (not found):
> ng-table/header.html
> Request error: The URL returned a 404 (not found):
> ng-table/pager.html

Then `DashBoard.controller.js`, all references to AngularJS views incorrectly refer to `/App_Plugins/uTransporter-dashboard/HelpDialog.html` which should be `/App_Plugins/uTransporter/HelpDialog.html`

After correcting the previous error, now the button `export` fails because it calls HTTP POST on `/umbraco/backoffice/API/UTransporter/StartUpGeneration` route which returns 404

This was fixed by adding [PluginController("API")] to `Controller\UTransporterController.cs`

**Comment by Korayem** [comment]
Thanks @rickvanschalkwijk !

Any plans on releasing the nuget with the fix? I am not trying to pressure you :)

**Comment by rickvanschalkwijk** [comment]
Yes! working on it :)

**Comment by Korayem** [comment]
Awesome! thanks :) :+1:
